version: "3.9"

services:
    app:
        container_name: web-portfolio
        image: web-portfolio
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
