baseURL = 'https://nathancmendoza.live/'
languageCode = 'en-us'
title = 'Nathan C. Mendoza'
theme = 'm10c'

[params]
    author = 'Nathan C. Mendoza'
    description = 'UCI Graduate'
    avatar = '/avatar.png'
    menu_item_separator = '</br>'
    favicon = '/favicon.ico'

[[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/nathancmendoza"

[[params.social]]
    icon = "linkedin"
    name = "My LinkedIn profile"
    url = "https://www.linkedin.com/in/nathan-mendoza-23b0a716b"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 20

[[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 30

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 40

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50
