name: Create Container Image

on:
  push:
    branches:
      - main
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout Site"
            uses: actions/checkout@v2

          - name: "Install Theme"
            working-directory: ./web-portfolio
            run: |
              wget -c https://github.com/hugo-toha/toha/archive/refs/tags/v3.8.0.tar.gz -O - | tar -xz
              mv toha-v3.8.0/* themes/toha && rm -rf toha-v3.8.0

          - name: "Setup hugo" 
            uses: peaceiris/actions-hugo@v2
            with:
              hugo-version: 0.118.0

          - name: "Generate Site"
            run: hugo --verbose
