name: Create Container Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Checkout Site"
        uses: actions/checkout@v2

      - name: "Install Theme"
        run: |
          wget -c https://github.com/hugo-toha/toha/archive/refs/tags/v3.8.0.tar.gz -O - | tar -xz
          mv toha-3.8.0/* themes/toha && rm -rf toha-3.8.0

      - name: "Setup hugo" 
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.118.0
          extended: true

      - name: "Generate Site"
        run: hugo --verbose
